import Head from 'next/head';
import Showcase from '../components/Showcase';
import FeatureCard from '../components/FeatureCard';
import Lessons from '../components/Lessons';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.png" type="image/x-icon" />
      </Head>
      <nav className="nextjs-nav sticky top-0 border-b bg-white">
        <div
          className="max-w-screen-lg mx-auto flex sm:hidden flex-row items-center gap-10 p-5"
          style={{ height: '80px' }}
        >
          <a href="#">
            <img src="/nextjs.svg" width={65} height={50} />
          </a>
          <a href="#learnnextjs" className="nav-button">
            LEARN
          </a>
        </div>
        <div
          className="max-w-screen-lg mx-auto hidden sm:flex flex-row items-center gap-10 p-5"
          style={{ height: '80px' }}
        >
          <a href="#">
            <img src="/nextjs.svg" width={65} height={50} />
          </a>
          <a href="#whatsnextjs" className="text-gray-500 hover:text-gray-700">
            WHAT'S NEXT.JS
          </a>
          <a
            href="#whosusingnextjs"
            className="text-gray-500 hover:text-gray-700"
          >
            WHO'S USING NEXT.JS
          </a>
          <a href="#learnnextjs" className="nav-button">
            LEARN
          </a>
        </div>
      </nav>
      <div
        className="py-28 px-5 flex flex-col items-center justify-center"
        style={{ minHeight: 'calc(100vh - 81px)' }}
      >
        <img src="/nextjs.svg" width={250} height={125} />
        <h2 className="font-semibold text-4xl text-center ">
          The React Framework for Production
        </h2>
        <p className="text-center max-w-lg mt-3">
          Next.js มอบประสบการณ์อันยอดเยี่ยมในการพัฒนาเว็บไซต์ด้วยฟีเจอร์ต่างๆ
          ที่คุณจำเป็น และไม่ต้อง config เองให้ยุ่งยากอีกต่อไป
        </p>
        <a href="#whatsnextjs" className="mt-10 button">
          LEARN MORE
        </a>
      </div>
      <div id="whatsnextjs" className="max-w-screen-lg mx-auto p-5 pt-28">
        <h1 className="text-center font-semibold text-3xl">Next.js คืออะไร</h1>
        <p className="mt-5">
          Next.js คือ Framework ที่ใช้สำหรับพัฒนาเว็บ (หรือเว็บแอพ)
          โดยใช้ขุมพลังของ React ซึ่งช่วยให้กระบวนการสร้างนั้นง่ายขึ้น
          ถูกสร้างขึ้น on top จาก library ที่เป็นที่นิยมอย่าง React, Webpack และ
          Babel ขึ้นมาอีกที จุดเด่นของ Next.js มีดังต่อไปนี้
        </p>
        <div className="text-center grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-10">
          <FeatureCard
            icon="construction"
            title="Zero Config"
            description="มีการทำ Compilation และ Bundling ให้อัตโนมัติ และ optimize มาตั้งแต่เริ่ม"
          />
          <FeatureCard
            icon="computer"
            title="SSR (server-side rendering)"
            description="มีลักษณะการทำงานเป็น SSR ทำให้ไม่ต้องกังวลเรื่องข้อจำกัดการทำ SEO"
          />
          <FeatureCard
            icon="account_tree"
            title="File-system Routing"
            description="ทุก component ใน /page จะถูกแปลงเป็น route"
          />
          <FeatureCard
            icon="file_download"
            title="Static HTML File Exportable"
            description="สามารถ Export เป็น Static HTML file ได้ "
          />
          <FeatureCard
            icon="code"
            title="TypeScript Support"
            description="นอกจากภาษา JavaScript แล้ว ยังรองรับการเขียนด้วยภาษา TypeScript"
          />
          <FeatureCard
            icon="style"
            title="Built-In CSS Support"
            description="กำหนด style ให้กับ component ด้วย CSS Modules และยังรองรับ Built-in Sass"
          />
        </div>
      </div>
      <div id="whosusingnextjs" className="max-w-screen-lg mx-auto p-5 pt-28 ">
        <h1 className="text-center font-semibold text-3xl">
          เว็บที่ใช้ Next.js
        </h1>
        <div className="mt-5">
          <Showcase />
        </div>
      </div>
      <div
        id="learnnextjs"
        className="min-h-screen max-w-screen-lg mx-auto p-5 pt-28 "
      >
        <h1 className="font-semibold text-3xl">สอนใช้ Next.js เบื้องต้น</h1>
        <p className="pt-5">
          เนื้อหาที่จะสอนใช้ Next.js ในครั้งนี้ จะประกอบไปด้วยการติดตั้ง
          การใช้งานเบื้องต้น และการทำ Page Routing
          สามารถอ่านเรื่องอื่นๆ เพิ่มเติมได้ที่{' '}
          <a
            href="https://nextjs.org/docs"
            target="_blank"
            className="text-gray-400 hover:text-gray-700"
          >
            Official Documentation ของ Next.js
          </a>{' '}
          ซึ่งเขียนไว้ได้อย่างละเอียดครบถ้วนและทำความเข้าใจได้ไม่ยากได้
        </p>
        <div className="grid grid-cols-1 md:grid-cols-4">
          <div className="pt-10 md:pt-28 md:sticky top-0" style={{maxHeight:'500px'}}>
            <ul className="flex flex-col gap-2">
              <li>
                <a
                  href="#lesson00"
                  className="text-gray-500 hover:text-gray-700"
                >
                  {'>'} เตรียมพร้อมก่อนลุย
                </a>
              </li>
              <li>
                <a
                  href="#lesson01"
                  className="text-gray-500 hover:text-gray-700"
                >
                  {'>'} สร้าง Next.js app
                </a>
              </li>
              <li>
                <a
                  href="#lesson02"
                  className="text-gray-500 hover:text-gray-700"
                >
                  {'>'} แก้ไขหน้า Home
                </a>
              </li>
              <li>
                <a
                  href="#lesson03"
                  className="text-gray-500 hover:text-gray-700"
                >
                  {'>'} แทรกไฟล์ static
                </a>
              </li>
              <li>
                <a
                  href="#lesson04"
                  className="text-gray-500 hover:text-gray-700"
                >
                  {'>'} หน้าและการทำ Routing <br/>ระหว่างหน้า
                </a>
              </li>
              <li>
                <a
                  href="#lesson05"
                  className="text-gray-500 hover:text-gray-700"
                >
                  {'>'} เพิ่ม Stylesheet
                </a>
              </li>
            </ul>
          </div>
          <div className="col-span-3">
            <Lessons/>
          </div>
        </div>
      </div>
    </>
  );
}
